### ISSUE TITLE
Future of This Module

### ISSUE THREAD

**Issue by librasteve** [samgwise/html-lazy#3]
Hi @samgwise 

I have been working in a new module - (working name HTML::Functional) - and just found that you already created the same idea here!

However, I see that this module is on CPAN and I understand that it needs to be moved to ZEF in the near future if it is to continue to be available via the zef package manager.

Are you planning to do this?
-or-
Would you be OK for me to fork this module, bump the version and publish with me as the author (I which case I would be taking on responsibility for maintenance going forward)?

~librasteve

**Comment by samgwise** [comment]
Hi librasteve,

Thanks for reaching out. I haven't been keeping up with raku news as much
lately and had missed there were ecosystem changes coming. I'm happy for
you to take over the module. I'll have to catch up on the zef changes for a
few other projects.

Happy coding!

**Comment by librasteve** [comment]
Hey, I have done a more detailed review of the source and API here and it seems that, while our general ideas are similar, my needs are a quite different at the detail level. 

So, I plan to go ahead with a parallel module ... apologies for the false alarm.
